In [6]:
import pandas as pd

df = pd.read_csv("IPL.csv", dtype=str)
print(df)

       Unnamed: 0 match_id        date match_type             event_name  \
0          141607   335982  2008-04-18        T20  Indian Premier League
1          141608   335982  2008-04-18        T20  Indian Premier League
2          141609   335982  2008-04-18        T20  Indian Premier League
3          141610   335982  2008-04-18        T20  Indian Premier League
4          141611   335982  2008-04-18        T20  Indian Premier League
...           ...      ...         ...        ...                    ...
283673     283673  1529267  2026-04-16        T20  Indian Premier League
283674     283674  1529267  2026-04-16        T20  Indian Premier League
283675     283675  1529267  2026-04-16        T20  Indian Premier League
283676     283676  1529267  2026-04-16        T20  Indian Premier League
283677     283677  1529267  2026-04-16        T20  Indian Premier League

       innings           batting_team                 bowling_team over ball  \
0            1  Kolkata Knight Riders  Royal Challengers Bangalore    0    1
1            1  Kolkata Knight Riders  Royal Challengers Bangalore    0    2
2            1  Kolkata Knight Riders  Royal Challengers Bangalore    0    3
3            1  Kolkata Knight Riders  Royal Challengers Bangalore    0    3
4            1  Kolkata Knight Riders  Royal Challengers Bangalore    0    4
...        ...                    ...                          ...  ...  ...
283673       2           Punjab Kings               Mumbai Indians   16    1
283674       2           Punjab Kings               Mumbai Indians   16    1
283675       2           Punjab Kings               Mumbai Indians   16    2
283676       2           Punjab Kings               Mumbai Indians   16    3
283677       2           Punjab Kings               Mumbai Indians   16    3

        ... team_balls team_wicket new_batter power_surge_start batter_runs  \
0       ...          1           0        NaN               NaN           0
1       ...          2           0        NaN               NaN           0
2       ...          2           0        NaN               NaN           0
3       ...          3           0        NaN               NaN           0
4       ...          4           0        NaN               NaN           0
...     ...        ...         ...        ...               ...         ...
283673  ...         96           3        NaN               NaN           2
283674  ...         97           3        NaN               NaN           2
283675  ...         98           3        NaN               NaN           6
283676  ...         98           3        NaN               NaN           6
283677  ...         99           3        NaN               NaN          10

       batter_balls bowler_wicket                  batting_partners  \
0                 1             0     ('BB McCullum', 'SC Ganguly')
1                 1             0     ('BB McCullum', 'SC Ganguly')
2                 1             0     ('BB McCullum', 'SC Ganguly')
3                 2             0     ('BB McCullum', 'SC Ganguly')
4                 3             0     ('BB McCullum', 'SC Ganguly')
...             ...           ...                               ...
283673            2             0  ('MP Stoinis', 'P Simran Singh')
283674            3             0  ('MP Stoinis', 'P Simran Singh')
283675            4             0  ('MP Stoinis', 'P Simran Singh')
283676            4             0  ('MP Stoinis', 'P Simran Singh')
283677            5             0  ('MP Stoinis', 'P Simran Singh')

       next_batter striker_out
0              NaN       False
1              NaN       False
2              NaN       False
3              NaN       False
4              NaN       False
...            ...         ...
283673         NaN       False
283674         NaN       False
283675         NaN       False
283676         NaN       False
283677         NaN       False

[283678 rows x 65 columns]

In [5]:
print(df.shape)

(283678, 65)

In [7]:
print(df.columns.tolist())

['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings', 'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter', 'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball', 'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary', 'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind', 'player_out', 'fielders', 'runs_target', 'review_batter', 'team_reviewed', 'review_decision', 'umpire', 'umpires_call', 'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner', 'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season', 'gender', 'team_type', 'superover_winner', 'result_type', 'method', 'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number', 'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter', 'striker_out']

In [8]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  object
 1   match_id           283678 non-null  object
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  object
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  object
 9   ball               283678 non-null  object
 10  ball_no            283678 non-null  object
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  object
 13  runs_batter        283678 non-null  object
 14  balls_faced        283678 non-null  object
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  object
 17  runs_extras        283678 non-null  object
 18  runs_total         283678 non-null  object
 19  runs_bowler        283678 non-null  object
 20  runs_not_boundary  283678 non-null  object
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  object
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  object
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  object
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  object
 41  month              283678 non-null  object
 42  year               283678 non-null  object
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  object
 50  overs              283678 non-null  object
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  object
 55  team_balls         283678 non-null  object
 56  team_wicket        283678 non-null  object
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       object
 59  batter_runs        283678 non-null  object
 60  batter_balls       283678 non-null  object
 61  bowler_wicket      283678 non-null  object
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  object
dtypes: object(65)
memory usage: 140.7+ MB

In [12]:
df.isnull().sum()

Unnamed: 0               0
match_id                 0
date                     0
match_type               0
event_name               0
                     ...
batter_balls             0
bowler_wicket            0
batting_partners         0
next_batter         270085
striker_out              0
Length: 65, dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df = df.drop_duplicates()

In [17]:
missing = df.isnull().sum()
missing[missing > 0]

extra_type           268185
wicket_kind          269572
player_out           269572
fielders             273433
runs_target          147168
review_batter        282771
team_reviewed        282771
review_decision      282771
umpire               282771
win_outcome            4724
superover_winner     279782
result_type          278954
method               279788
new_batter           270085
power_surge_start    283678
next_batter          270085
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop(columns=['Unnamed: 0'])

In [20]:
df = df.drop(columns=['next_batter'])

In [21]:
df.shape

(283678, 63)

In [23]:
df.columns.tolist()

['match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'striker_out']

In [24]:
df[['runs_batter','balls_faced','bowler_wicket']].dtypes

runs_batter      object
balls_faced      object
bowler_wicket    object
dtype: object

In [25]:
'next_batter' in df.columns

False

In [26]:
sorted(df['batting_team'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiant',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [33]:
team_mapping = {
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings',
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
    'Rising Pune Supergiant':'Rising Pune Supergiants',
    'Gujarat Lions': 'Gujarat Titans',
    'Pune Warriors': 'Rising Pune Supergiants'
}

In [34]:
df['batting_team'] = df['batting_team'].replace(team_mapping)

In [35]:
df['bowling_team'] = df['bowling_team'].replace(team_mapping)

In [36]:
df['match_won_by'] = df['match_won_by'].replace(team_mapping)

In [37]:
df['toss_winner'] = df['toss_winner'].replace(team_mapping)

In [38]:
sorted(df['batting_team'].unique())

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Gujarat Titans',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiants',
 'Royal Challengers Bengaluru',
 'Sunrisers Hyderabad']

In [39]:
df['batter'].nunique()

719

In [41]:
sorted(df['batter'].unique())

['A Ashish Reddy',
 'A Badoni',
 'A Chandila',
 'A Chopra',
 'A Choudhary',
 'A Dananjaya',
 'A Flintoff',
 'A Kamboj',
 'A Kumble',
 'A Manohar',
 'A Mhatre',
 'A Mishra',
 'A Mithun',
 'A Mukund',
 'A Nehra',
 'A Nortje',
 'A Raghuvanshi',
 'A Singh',
 'A Symonds',
 'A Tomar',
 'A Uniyal',
 'A Zampa',
 'AA Bilakhia',
 'AA Chavan',
 'AA Jhunjhunwala',
 'AA Kulkarni',
 'AA Noffke',
 'AB Agarkar',
 'AB Barath',
 'AB Dinda',
 'AB McDonald',
 'AB de Villiers',
 'AC Blizzard',
 'AC Gilchrist',
 'AC Thomas',
 'AC Voges',
 'AD Hales',
 'AD Mascarenhas',
 'AD Mathews',
 'AD Nath',
 'AD Russell',
 'AF Milne',
 'AG Murtaza',
 'AG Paunikar',
 'AJ Finch',
 'AJ Hosein',
 'AJ Turner',
 'AJ Tye',
 'AK Markram',
 'AL Menaria',
 'AM Nayar',
 'AM Rahane',
 'AN Ahmed',
 'AN Ghosh',
 'AP Dole',
 'AP Majumdar',
 'AP Tare',
 'AR Bawne',
 'AR Patel',
 'AS Joseph',
 'AS Rajpoot',
 'AS Raut',
 'AS Roy',
 'AS Yadav',
 'AT Carey',
 'AT Rayudu',
 'AU Rashid',
 'AUK Pathan',
 'Abdul Basith',
 'Abdul Samad',
 'Abdur Razzak',
 'Abhishek Sharma',
 'Abishek Porel',
 'Akash Deep',
 'Akash Madhwal',
 'Aman Hakim Khan',
 'Aniket Verma',
 'Anirudh Singh',
 'Ankit Sharma',
 'Ankit Soni',
 'Anmolpreet Singh',
 'Anuj Rawat',
 'Anureet Singh',
 'Arjun Tendulkar',
 'Arshad Khan',
 'Arshad Khan (2)',
 'Arshdeep Singh',
 'Ashok Sharma',
 'Ashutosh Sharma',
 'Atharva Taide',
 'Auqib Nabi',
 'Avesh Khan',
 'Azhar Mahmood',
 'Azmatullah Omarzai',
 'B Akhil',
 'B Chipli',
 'B Indrajith',
 'B Kumar',
 'B Laughlin',
 'B Lee',
 'B Sai Sudharsan',
 'B Stanlake',
 'B Sumanth',
 'BA Bhatt',
 'BA Stokes',
 'BAW Mendis',
 'BB McCullum',
 'BB Samantray',
 'BB Sran',
 'BCJ Cutting',
 'BE Hendricks',
 'BJ Haddin',
 'BJ Hodge',
 'BJ Rohrer',
 'BKG Mendis',
 'BMAJ Mendis',
 'BR Dunk',
 'BR Sharath',
 'Basil Thampi',
 'Bipul Sharma',
 'C Bosch',
 'C Connolly',
 'C Green',
 'C Madan',
 'C Munro',
 'C Nanda',
 'C Sakariya',
 'C de Grandhomme',
 'CA Ingram',
 'CA Lynn',
 'CA Pujara',
 'CH Gayle',
 'CH Morris',
 'CJ Anderson',
 'CJ Ferguson',
 'CJ Jordan',
 'CJ McKay',
 'CK Kapugedera',
 'CK Langeveldt',
 'CL White',
 'CM Gautam',
 'CR Brathwaite',
 'CR Woakes',
 'CRD Fernando',
 'CV Varun',
 'D Brevis',
 'D Ferreira',
 'D Kalyankrishna',
 'D Padikkal',
 'D Pretorius',
 'D Salunkhe',
 'D Wiese',
 'D du Preez',
 'DA Miller',
 'DA Payne',
 'DA Warner',
 'DAJ Bracewell',
 'DB Das',
 'DB Ravi Teja',
 'DE Bollinger',
 'DG Nalkande',
 'DH Yagnik',
 'DJ Bravo',
 'DJ Harris',
 'DJ Hooda',
 'DJ Hussey',
 'DJ Jacobs',
 'DJ Malan',
 'DJ Mitchell',
 'DJ Muthuswami',
 'DJ Thornely',
 'DJ Willey',
 'DJG Sammy',
 'DJM Short',
 'DL Chahar',
 'DL Vettori',
 'DM Bravo',
 'DNT Zoysa',
 'DP Conway',
 'DP Nannes',
 'DP Vijaykumar',
 'DPMD Jayawardene',
 'DR Martyn',
 'DR Sams',
 'DR Shorey',
 'DR Smith',
 'DS Kulkarni',
 'DS Lehmann',
 'DS Rathi',
 'DT Christian',
 'DT Patil',
 'DW Steyn',
 'Dhruv Jurel',
 'E Lewis',
 'EJG Morgan',
 'ER Dwivedi',
 'F Behardien',
 'F du Plessis',
 'FA Allen',
 'FH Allen',
 'FH Edwards',
 'FY Fazal',
 'Fazalhaq Farooqi',
 'G Coetzee',
 'G Gambhir',
 'GB Hogg',
 'GC Smith',
 'GC Viljoen',
 'GD McGrath',
 'GD Phillips',
 'GF Linde',
 'GH Vihari',
 'GHS Garton',
 'GJ Bailey',
 'GJ Maxwell',
 'GR Napier',
 'Gulbadin Naib',
 'Gurkeerat Singh',
 'H Das',
 'H Klaasen',
 'HC Brook',
 'HE van der Dussen',
 'HF Gurney',
 'HH Gibbs',
 'HH Pandya',
 'HM Amla',
 'HR Shokeen',
 'HV Patel',
 'Harbhajan Singh',
 'Harmeet Singh',
 'Harpreet Brar',
 'Harpreet Singh',
 'Harsh Dubey',
 'Harshit Rana',
 'I Malhotra',
 'I Sharma',
 'I Udana',
 'IC Pandey',
 'IK Pathan',
 'IR Jaggi',
 'IS Sodhi',
 'Imran Tahir',
 'Iqbal Abdulla',
 'Ishan Kishan',
 'J Arunkumar',
 'J Botha',
 'J Fraser-McGurk',
 'J Overton',
 'J Suchith',
 'J Syed Mohammad',
 'J Theron',
 'J Yadav',
 'JA Morkel',
 'JA Richardson',
 'JC Archer',
 'JC Buttler',
 'JD Ryder',
 'JD Unadkat',
 'JDP Oram',
 'JDS Neesham',
 'JE Root',
 'JE Taylor',
 'JEC Franklin',
 'JG Bethell',
 'JH Kallis',
 'JJ Bumrah',
 'JJ Roy',
 'JJ van der Wath',
 'JL Denly',
 'JL Pattinson',
 'JM Bairstow',
 'JM Kemp',
 'JM Sharma',
 'JO Holder',
 'JP Behrendorff',
 'JP Duminy',
 'JP Faulkner',
 'JP Inglis',
 'JPR Scantlebury-Searles',
 'JR Hazlewood',
 'JR Hopes',
 'JR Philippe',
 'Jaskaran Singh',
 'Joginder Sharma',
 'K Goel',
 'K Gowtham',
 'K Kartikeya',
 'K Rabada',
 'K Upadhyay',
 'K Yadav',
 'KA Jamieson',
 'KA Maharaj',
 'KA Pollard',
 'KAJ Roach',
 'KB Arun Karthik',
 'KC Cariappa',
 'KC Sangakkara',
 'KD Karthik',
 'KH Pandya',
 'KJ Abbott',
 'KK Ahmed',
 'KK Cooper',
 'KK Nair',
 'KL Nagarkoti',
 'KL Rahul',
 'KM Asif',
 'KM Jadhav',
 'KMA Paul',
 'KMDN Kulasekara',
 'KP Appanna',
 'KP Pietersen',
 'KR Mayers',
 'KR Sen',
 'KS Bharat',
 'KS Rathore',
 'KS Sharma',
 'KS Williamson',
 'KT Maphaka',
 'KV Sharma',
 'KW Richardson',
 'Kamran Akmal',
 'Kamran Khan',
 'Karanveer Singh',
 'Kartik Sharma',
 'Kartik Tyagi',
 'Kuldeep Yadav',
 'Kumar Kushagra',
 'L Ablish',
 'L Balaji',
 'L Ngidi',
 'L Ronchi',
 'L Wood',
 'LA Carseldine',
 'LA Pomersbach',
 'LB Williams',
 'LE Plunkett',
 'LG Pretorius',
 'LH Ferguson',
 'LJ Wright',
 'LMP Simmons',
 'LPC Silva',
 'LR Shukla',
 'LRPL Taylor',
 'LS Livingstone',
 'Lalit Yadav',
 'Liton Das',
 'M Ashwin',
 'M Jansen',
 'M Kaif',
 'M Kartik',
 'M Klinger',
 'M Manhas',
 'M Markande',
 'M Morkel',
 'M Muralitharan',
 'M Ntini',
 'M Prasidh Krishna',
 'M Rawat',
 'M Shahrukh Khan',
 'M Theekshana',
 'M Tiwari',
 'M Vijay',
 'M Vohra',
 'M de Lange',
 'MA Agarwal',
 'MA Khote',
 'MA Starc',
 'MA Wood',
 'MC Henriques',
 'MC Juneja',
 'MD Choudhary',
 'MD Mishra',
 'MD Shanaka',
 'MDKJ Perera',
 'MEK Hussey',
 'MF Maharoof',
 'MG Bracewell',
 'MG Johnson',
 'MJ Clarke',
 'MJ Guptill',
 'MJ Henry',
 'MJ Lumb',
 'MJ McClenaghan',
 'MJ Owen',
 'MJ Santner',
 'MJ Suthar',
 'MK Lomror',
 'MK Pandey',
 'MK Tiwary',
 'ML Hayden',
 'MM Ali',
 'MM Patel',
 'MM Sharma',
 'MN Samuels',
 'MN van Wyk',
 'MP Breetzke',
 'MP Stoinis',
 'MR Marsh',
 'MS Bhandage',
 'MS Bisla',
 'MS Dhoni',
 'MS Gony',
 'MS Wade',
 'MV Boucher',
 'MW Short',
 'Mandeep Singh',
 'Mashrafe Mortaza',
 'Mayank Dagar',
 'Misbah-ul-Haq',
 'Mohammad Ashraful',
 'Mohammad Asif',
 'Mohammad Hafeez',
 'Mohammad Nabi',
 'Mohammed Shami',
 'Mohammed Siraj',
 'Mohit Rathee',
 'Mohsin Khan',
 'Mujeeb Ur Rahman',
 'Mukesh Choudhary',
 'Mukesh Kumar',
 'Musheer Khan',
 'Mustafizur Rahman',
 'N Burger',
 'N Jagadeesan',
 'N Pooran',
 'N Rana',
 'N Saini',
 'N Wadhera',
 'ND Doshi',
 'NJ Maddinson',
 'NJ Rimmington',
 'NK Patel',
 'NL McCullum',
 'NLTC Perera',
 'NM Coulter-Nile',
 'NS Naik',
 'NT Ellis',
 'NV Ojha',
 'Naman Dhir',
 'Navdeep Saini',
 'Naveen-ul-Haq',
 'Nithish Kumar Reddy',
 'Noor Ahmad',
 'OA Shah',
 'OC McCoy',
 'OF Smith',
 'P Awana',
 'P Chopra',
 'P Dogra',
 'P Dubey',
 'P Kumar',
 'P Negi',
 'P Nissanka',
 'P Parameswaran',
 'P Ray Barman',
 'P Sahu',
 'P Simran Singh',
 'PA Patel',
 'PA Reddy',
 'PBB Rajapaksa',
 'PC Valthaty',
 'PD Collingwood',
 'PD Salt',
 'PHKD Mendis',
 'PJ Cummins',
 'PJ Sangwan',
 'PK Garg',
 'PM Sarvesh Kumar',
 'PN Mankad',
 'PP Chawla',
 'PP Ojha',
 'PP Shaw',
 'PR Shah',
 'PR Veer',
 'PSP Handscomb',
 'PV Tambe',
 'PVD Chameera',
 'PVSN Raju',
 'PWA Mulder',
 'PWH de Silva',
 'Pankaj Singh',
 'Parvez Rasool',
 'Prince Yadav',
 'Priyansh Arya',
 'Q de Kock',
 'R Ashwin',
 'R Bhatia',
 'R Bishnoi',
 'R Dhawan',
 'R Dravid',
 'R McLaren',
 'R Minz',
 'R Ninan',
 'R Parag',
 'R Powell',
 'R Rampaul',
 'R Ravindra',
 'R Sai Kishore',
 'R Sanjay Yadav',
 'R Sathish',
 'R Sharma',
 'R Shepherd',
 'R Shukla',
 'R Tewatia',
 'R Vinay Kumar',
 'RA Bawa',
 'RA Jadeja',
 'RA Tripathi',
 'RD Chahar',
 'RD Gaikwad',
 'RD Rickelton',
 'RE Levi',
 'RE van der Merwe',
 'RG More',
 'RG Sharma',
 'RJ Gleeson',
 'RJ Harris',
 'RJ Peterson',
 'RJ Quiney',
 'RJW Topley',
 'RK Bhui',
 'RK Singh',
 'RM Patidar',
 'RN ten Doeschate',
 'RP Meredith',
 'RP Singh',
 'RR Bhatkal',
 'RR Pant',
 'RR Powar',
 'RR Raje',
 'RR Rossouw',
 'RR Sarwan',
 'RS Bopara',
 'RS Gavaskar',
 'RS Sodhi',
 'RT Ponting',
 'RV Gomez',
 'RV Patel',
 'RV Uthappa',
 'Rahmanullah Gurbaz',
 'Ramandeep Singh',
 'Rashid Khan',
 'Rasikh Salam',
 'Ravi Bishnoi',
 'S Anirudha',
 'S Aravind',
 'S Arora',
 'S Badree',
 'S Badrinath',
 'S Chanderpaul',
 'S Dhawan',
 'S Dube',
 'S Gopal',
 'S Kaul',
 'S Kaushik',
 'S Ladda',
 'S Lamichhane',
 'S Nadeem',
 'S Narwal',
 'S Rana',
 'S Randiv',
 'S Sohal',
 'S Sreesanth',
 'S Sriram',
 'S Tyagi',
 'S Vidyut',
 'SA Abbott',
 'SA Asnodkar',
 'SA Yadav',
 'SB Bangar',
 'SB Dubey',
 'SB Jakati',
 'SB Joshi',
 'SB Styris',
 'SB Wagh',
 'SC Ganguly',
 'SD Chitnis',
 'SD Hope',
 'SD Lad',
 'SE Bond',
 'SE Marsh',
 'SE Rutherford',
 'SH Johnson',
 'SJ Srivastava',
 'SK Raina',
 'SK Rasheed',
 'SK Trivedi',
 'SK Warne',
 'SL Malinga',
 'SM Curran',
 'SM Harwood',
 'SM Katich',
 'SM Pollock',
 'SMSM Senanayake',
 'SN Khan',
 'SN Thakur',
 'SO Hetmyer',
 'SP Fleming',
 'SP Goswami',
 'SP Jackson',
 'SP Narine',
 'SPD Smith',
 'SR Tendulkar',
 'SR Watson',
 'SS Cottrell',
 'SS Iyer',
 'SS Prabhudessai',
 'SS Shaikh',
 'SS Tiwary',
 'ST Jayasuriya',
 'STR Binny',
 'SV Samson',
 'SW Billings',
 'SW Tait',
 'SZ Mulani',
 'Sachin Baby',
 'Salman Butt',
 'Sameer Rizvi',
 'Sandeep Sharma',
 'Sanvir Singh',
 'Saurav Chauhan',
 'Sediqullah Atal',
 'Shahbaz Ahmed',
 'Shahid Afridi',
 'Shakib Al Hasan',
 'Shashank Singh',
 'Shivam Mavi',
 'Shivam Sharma',
 'Shivam Singh',
 'Shivang Kumar',
 'Shoaib Ahmed',
 'Shoaib Akhtar',
 'Shoaib Malik',
 'Shubman Gill',
 'Sikandar Raza',
 'Simarjeet Singh',
 'Sohail Tanvir',
 'Sumit Kumar',
 'Sunny Gupta',
 'Sunny Singh',
 'Suryansh Shedge',
 'Swapnil Singh',
 'T Banton',
 'T Henderson',
 'T Kohler-Cadmore',
 'T Kohli',
 'T Natarajan',
 'T Shamsi',
 'T Stubbs',
 'T Taibu',
 'T Thushara',
 'TA Boult',
 'TD Paine',
 'TG Southee',
 'TH David',
 'TK Curran',
 'TL Seifert',
 'TL Suman',
 'TM Dilshan',
 'TM Head',
 'TM Srivastava',
 'TR Birt',
 'TS Mills',
 'TU Deshpande',
 'Tanush Kotian',
 'Tilak Varma',
 'U Kaul',
 'UA Birla',
 'UBT Chand',
 'UT Khawaja',
 'UT Yadav',
 'Umar Gul',
 'Umran Malik',
 'Urvil Patel',
 'V Kohli',
 'V Nigam',
 'V Pratap Singh',
 'V Sehwag',
 'V Shankar',
 'V Suryavanshi',
 'V Viyaskanth',
 'VG Arora',
 'VH Zol',
 'VR Aaron',
 'VR Iyer',
 'VRV Singh',
 'VS Malik',
 'VS Yeligati',
 'VVS Laxman',
 'VY Mahesh',
 'Vijaykumar Vyshak',
 'Virat Singh',
 'Vishnu Vinod',
 'Vivrant Sharma',
 'W Jaffer',
 'WA Mota',
 'WD Parnell',
 'WG Jacks',
 'WP Saha',
 'WPUJC Vaas',
 'Washington Sundar',
 'X Thalaivan Sargunam',
 'XC Bartlett',
 'Y Gnaneswara Rao',
 'Y Nagar',
 'Y Prithvi Raj',
 'Y Venugopal Rao',
 'YA Abdulla',
 'YBK Jaiswal',
 'YK Pathan',
 'YS Chahal',
 'YV Dhull',
 'YV Takawale',
 'Yash Dayal',
 'Yashpal Singh',
 'Younis Khan',
 'Yudhvir Singh',
 'Yuvraj Singh',
 'Z Khan']

In [43]:
[player for player in df['batter'].unique() if 'Kohli' in player]

['V Kohli', 'T Kohli']

In [44]:
df[df['batter'].isin(['Arshad Khan','Arshad Khan (2)'])][
    ['batter','batting_team','season']
].drop_duplicates()

                 batter          batting_team season
227024      Arshad Khan        Mumbai Indians   2023
250019      Arshad Khan  Lucknow Super Giants   2024
250544  Arshad Khan (2)  Lucknow Super Giants   2024
262146      Arshad Khan        Gujarat Titans   2025

In [45]:
df[['runs_batter','balls_faced','bowler_wicket']].dtypes

runs_batter      object
balls_faced      object
bowler_wicket    object
dtype: object

In [46]:
df['runs_batter'] = pd.to_numeric(df['runs_batter'], errors='coerce')
df['balls_faced'] = pd.to_numeric(df['balls_faced'], errors='coerce')
df['bowler_wicket'] = pd.to_numeric(df['bowler_wicket'], errors='coerce')

In [47]:
df[['runs_batter','balls_faced','bowler_wicket']].dtypes

runs_batter      int64
balls_faced      int64
bowler_wicket    int64
dtype: object

In [48]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

power_surge_start    283678
team_reviewed        282771
review_batter        282771
review_decision      282771
umpire               282771
method               279788
superover_winner     279782
result_type          278954
fielders             273433
new_batter           270085
player_out           269572
wicket_kind          269572
extra_type           268185
runs_target          147168
win_outcome            4724
dtype: int64

In [49]:
drop_cols = [
    'power_surge_start',
    'review_batter',
    'team_reviewed',
    'review_decision',
    'umpire',
    'method'
]

df = df.drop(columns=drop_cols, errors='ignore')

In [50]:
print(df['batting_team'].nunique())
print(df['bowling_team'].nunique())
print(df['city'].nunique())
print(df['venue'].nunique())

13
13
38
59

In [51]:
sorted(df['city'].dropna().unique())

['Abu Dhabi',
 'Ahmedabad',
 'Bangalore',
 'Bengaluru',
 'Bloemfontein',
 'Cape Town',
 'Centurion',
 'Chandigarh',
 'Chennai',
 'Cuttack',
 'Delhi',
 'Dharamsala',
 'Dubai',
 'Durban',
 'East London',
 'Guwahati',
 'Hyderabad',
 'Indore',
 'Jaipur',
 'Johannesburg',
 'Kanpur',
 'Kimberley',
 'Kochi',
 'Kolkata',
 'Lucknow',
 'Mohali',
 'Mumbai',
 'Nagpur',
 'Navi Mumbai',
 'New Chandigarh',
 'Port Elizabeth',
 'Pune',
 'Raipur',
 'Rajkot',
 'Ranchi',
 'Sharjah',
 'Unknown',
 'Visakhapatnam']

In [54]:
df['city'] = df['city'].replace({
    'Bangalore':'Bengaluru',
    'New Chandigarh': 'Chandigarh',
    'Chandigarh': 'Mohali'
})

In [53]:
sorted(df['city'].dropna().unique())

['Abu Dhabi',
 'Ahmedabad',
 'Bengaluru',
 'Bloemfontein',
 'Cape Town',
 'Centurion',
 'Chandigarh',
 'Chennai',
 'Cuttack',
 'Delhi',
 'Dharamsala',
 'Dubai',
 'Durban',
 'East London',
 'Guwahati',
 'Hyderabad',
 'Indore',
 'Jaipur',
 'Johannesburg',
 'Kanpur',
 'Kimberley',
 'Kochi',
 'Kolkata',
 'Lucknow',
 'Mohali',
 'Mumbai',
 'Nagpur',
 'Navi Mumbai',
 'Port Elizabeth',
 'Pune',
 'Raipur',
 'Rajkot',
 'Ranchi',
 'Sharjah',
 'Unknown',
 'Visakhapatnam']

In [55]:
df[df['city']=='Unknown'].shape

(12397, 57)

In [56]:
sorted(df['venue'].dropna().unique())

['Arun Jaitley Stadium',
 'Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium',
 'Eden Gardens',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium',
 'M Chinnaswamy Stadium, Bengaluru',
 'M.Chinnaswamy Stadium',
 'MA Chidambaram Stadium',
 'MA Chidambaram Stadium, Chepauk',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',
 'Maharashtra Cricket Association Stadium',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association IS Bindra Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Punjab Cricket Association Stadium, Mohali',
 'Rajiv Gandhi International Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel Stadium, Motera',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [64]:
venue_mapping = {

'Feroz Shah Kotla':
'Arun Jaitley Stadium, Delhi',

'Arun Jaitley Stadium':
'Arun Jaitley Stadium, Delhi',

'M.Chinnaswamy Stadium':
'M Chinnaswamy Stadium, Bengaluru',

'M Chinnaswamy Stadium':
'M Chinnaswamy Stadium, Bengaluru',

'Eden Gardens':
'Eden Gardens, Kolkata',

'Wankhede Stadium':
'Wankhede Stadium, Mumbai',

'Brabourne Stadium':
'Brabourne Stadium, Mumbai',

'Dr DY Patil Sports Academy':
'Dr DY Patil Sports Academy, Mumbai',

'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium':
'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',

'Himachal Pradesh Cricket Association Stadium':
'Himachal Pradesh Cricket Association Stadium, Dharamsala',

'MA Chidambaram Stadium':
'MA Chidambaram Stadium, Chepauk, Chennai',

'MA Chidambaram Stadium, Chepauk':
'MA Chidambaram Stadium, Chepauk, Chennai',

'Punjab Cricket Association IS Bindra Stadium':
'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',

'Punjab Cricket Association IS Bindra Stadium, Mohali':
'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',

'Punjab Cricket Association Stadium, Mohali':
'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',

'Rajiv Gandhi International Stadium':
'Rajiv Gandhi International Stadium, Uppal, Hyderabad',

'Rajiv Gandhi International Stadium, Uppal':
'Rajiv Gandhi International Stadium, Uppal, Hyderabad',

'Sawai Mansingh Stadium':
'Sawai Mansingh Stadium, Jaipur',

'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':
'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',

'Maharashtra Cricket Association Stadium':
'Maharashtra Cricket Association Stadium, Pune',

'Sardar Patel Stadium, Motera':
'Narendra Modi Stadium, Ahmedabad'

}

df['venue'] = df['venue'].replace(venue_mapping)

In [65]:
sorted(df['venue'].unique())

['Arun Jaitley Stadium, Delhi',
 'Barabati Stadium',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park',
 'De Beers Diamond Oval',
 'Dr DY Patil Sports Academy, Mumbai',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium',
 'Eden Gardens, Kolkata',
 'Green Park',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Holkar Cricket Stadium',
 'JSCA International Stadium Complex',
 'Kingsmead',
 'M Chinnaswamy Stadium, Bengaluru',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium',
 'New Wanderers Stadium',
 'Newlands',
 'OUTsurance Oval',
 'Punjab Cricket Association Stadium',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Saurashtra Cricket Association Stadium',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium',
 'Sharjah Cricket Stadium',
 'Sheikh Zayed Stadium',
 "St George's Park",
 'Subrata Roy Sahara Stadium',
 'SuperSport Park',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

In [66]:
df[['runs_batter','balls_faced','bowler_wicket']].describe()

         runs_batter    balls_faced  bowler_wicket
count  283678.000000  283678.000000  283678.000000
mean        1.281421       0.967082       0.045530
std         1.655126       0.178421       0.208465
min         0.000000       0.000000       0.000000
25%         0.000000       1.000000       0.000000
50%         1.000000       1.000000       0.000000
75%         1.000000       1.000000       0.000000
max         6.000000       1.000000       1.000000

In [67]:
(df['runs_batter'] < 0).sum()

np.int64(0)

In [68]:
(df['balls_faced'] < 0).sum()

np.int64(0)

In [69]:
(df['bowler_wicket'] < 0).sum()

np.int64(0)

In [70]:
# Exploratory Data Analysis (EDA)

In [72]:
#Player Stats Dataset
player_stats = df.groupby('batter').agg(
    total_runs=('runs_batter','sum'),
    balls=('balls_faced','sum'),
    matches=('match_id','nunique')
).reset_index()

player_stats.head()

           batter  total_runs  balls  matches
0  A Ashish Reddy         280    193       23
1        A Badoni        1076    776       51
2      A Chandila           4      7        2
3        A Chopra          53     71        6
4     A Choudhary          25     20        3

In [73]:
#Strike Rate
player_stats['strike_rate'] = (
    player_stats['total_runs']
    /
    player_stats['balls']
) * 100

In [75]:
#Top Run Scorers
player_stats.sort_values(
    'total_runs',
    ascending=False
).head(10)

             batter  total_runs  balls  matches  strike_rate
674         V Kohli        8899   6667      264   133.478326
514       RG Sharma        7185   5420      270   132.564576
550        S Dhawan        6769   5326      221   127.093504
155       DA Warner        6567   4702      184   139.663973
584        SK Raina        5536   4046      200   136.826495
400        MS Dhoni        5439   3957      241   137.452616
304        KL Rahul        5346   3914      139   136.586612
51        AM Rahane        5184   4127      188   125.611825
31   AB de Villiers        5181   3411      170   151.890941
131        CH Gayle        4997   3346      141   149.342499

In [76]:
#Bowling Stats
bowling_stats = df.groupby('bowler').agg(
    wickets=('bowler_wicket','sum')
).reset_index()

In [77]:
player_stats = player_stats.merge(
    bowling_stats,
    left_on='batter',
    right_on='bowler',
    how='left'
)

player_stats['wickets'] = player_stats['wickets'].fillna(0)

In [78]:
player_stats.head()

,batter,total_runs,balls,matches,strike_rate,bowler,wickets
0,A Ashish Reddy,280,193,23,145.077720,A Ashish Reddy,18.0
1,A Badoni,1076,776,51,138.659794,A Badoni,4.0
2,A Chandila,4,7,2,57.142857,A Chandila,11.0
3,A Chopra,53,71,6,74.647887,NaN,0.0
4,A Choudhary,25,20,3,125.000000,A Choudhary,5.0

In [79]:
player_stats.columns

Index(['batter', 'total_runs', 'balls', 'matches', 'strike_rate', 'bowler',
       'wickets'],
      dtype='object')

In [80]:
player_stats = player_stats.rename(
    columns={'batter':'player'}
)

In [81]:
player_stats = player_stats.drop(columns=['bowler'])

In [82]:
df.columns.tolist()

['match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'striker_out']

In [83]:
# Phase 1: Batter Valuation Model

In [95]:
batters = player_stats[
    (player_stats['total_runs'] >= 1000) &
    (player_stats['wickets'] < 30)
].copy()

In [96]:
batters.shape

(89, 6)

In [97]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

batters[['runs_score',
         'sr_score',
         'match_score']] = scaler.fit_transform(
    batters[['total_runs',
             'strike_rate',
             'matches']]
)

In [98]:
batters['batter_score'] = (
    batters['runs_score'] * 0.60 +
    batters['sr_score'] * 0.25 +
    batters['match_score'] * 0.15
) * 100

In [105]:
batters['estimated_price_cr'] = (
    0.2 +
    (batters['batter_score']/100)*24.8
)

In [106]:
top_batters = batters.sort_values(
    'estimated_price_cr',
    ascending=False
)[[
    'player',
    'total_runs',
    'strike_rate',
    'matches',
    'wickets',
    'batter_score',
    'estimated_price_cr'
]]

top_batters.head(15)

,player,total_runs,strike_rate,matches,wickets,batter_score,estimated_price_cr
674,V Kohli,8899,133.478326,264,4.0,84.410745,21.133865
514,RG Sharma,7185,132.564576,270,15.0,71.426451,17.913760
155,DA Warner,6567,139.663973,184,0.0,64.005179,16.073284
550,S Dhawan,6769,127.093504,221,4.0,63.222094,15.879079
400,MS Dhoni,5439,137.452616,241,0.0,58.157820,14.623139
31,AB de Villiers,5181,151.890941,170,0.0,57.093200,14.359114
584,SK Raina,5536,136.826495,200,25.0,56.123722,14.118683
131,CH Gayle,4997,149.342499,141,18.0,52.963050,13.334836
297,KD Karthik,4843,135.279330,233,0.0,52.337029,13.179583
611,SV Samson,4889,140.085960,176,0.0,50.916572,12.827310
304,KL Rahul,5346,136.586612,139,0.0,50.811334,12.801211
568,SA Yadav,4417,148.670481,156,0.0,49.240117,12.411549
538,RV Uthappa,4954,130.334123,197,0.0,49.134899,12.385455
51,AM Rahane,5184,125.611825,188,1.0,48.592115,12.250844
197,F du Plessis,4773,135.789474,147,0.0,46.661799,11.772126

In [107]:
# The estimated auction value of batters was calculated using:
# - Runs (60%)
# - Strike Rate (25%)
# - Matches Played (15%)

# The final score was scaled between ₹0.2 Cr and ₹25 Cr to simulate realistic IPL auction pricing.

In [108]:
# ============================================================
# IPL BATTER VALUATION MODEL
# ============================================================

# BUSINESS PROBLEM:
#
# IPL franchises invest crores of rupees during player auctions.
# However, selecting the right batter at the right price is a
# major challenge. Overpaying for an underperforming player or
# underestimating a consistent performer can negatively impact
# team performance and budget allocation.
#
# To solve this problem, a Data-Driven Batter Valuation Model
# was developed using historical IPL performance data.

# ============================================================
# OBJECTIVE
# ============================================================
#
# To estimate the fair auction value of a batter based on:
# 1. Total Runs Scored
# 2. Strike Rate
# 3. Matches Played (Experience)
#
# The model helps franchises make informed auction decisions
# instead of relying only on reputation or intuition.

# ============================================================
# FEATURES USED
# ============================================================
#
# 1. TOTAL RUNS (Weight: 60%)
#    - Measures consistency and batting performance.
#    - Higher runs indicate greater contribution to the team.
#
# 2. STRIKE RATE (Weight: 25%)
#    - Measures scoring speed in T20 cricket.
#    - Higher strike rate indicates aggressive and impactful batting.
#
# 3. MATCHES PLAYED (Weight: 15%)
#    - Represents player experience.
#    - Experienced players are generally more reliable in
#      high-pressure situations.

# ============================================================
# PLAYER SCORE CALCULATION
# ============================================================
#
# All performance metrics were normalized using MinMax Scaling
# to bring them onto the same scale.
#
# Batter Score Formula:
#
# Batter Score =
# (Runs Score × 60%)
# + (Strike Rate Score × 25%)
# + (Match Experience Score × 15%)
#
# Final score is calculated on a scale of 0–100.

# ============================================================
# AUCTION PRICE ESTIMATION
# ============================================================
#
# IPL auctions have a minimum base price for players.
#
# Assumptions:
# Minimum Auction Price = ₹20 Lakh (0.20 Cr)
# Maximum Auction Price = ₹25 Crore
#
# Estimated Auction Price Formula:
#
# Estimated Price (Cr) =
# 0.20 + (Batter Score / 100) × 24.80
#
# This ensures:
# - No player value falls below the IPL base price.
# - Elite players can reach realistic IPL valuation ranges.

# ============================================================
# BUSINESS INSIGHTS
# ============================================================
#
# Players with:
# - High run accumulation
# - Strong strike rates
# - Significant IPL experience
#
# receive higher valuation scores and estimated auction prices.
#
# Example:
# Virat Kohli achieved the highest valuation due to:
# - Highest run tally
# - Consistent performance
# - Extensive IPL experience
#
# Estimated Auction Value:
# ₹21+ Crore

# ============================================================
# CONCLUSION
# ============================================================
#
# This Batter Valuation Model converts historical player
# performance into an estimated auction value.
#
# The model provides franchises with a data-driven framework
# for evaluating batters and reducing investment risk during
# IPL auctions.
#
# Instead of relying solely on popularity or subjective
# judgment, teams can use objective performance metrics to
# make smarter auction decisions.
#
# ============================================================

In [109]:
# IPL BOWLER VALUATION MODEL

In [119]:
# BOWLER DATASET

# Ensure numeric columns

df['runs_bowler'] = pd.to_numeric(df['runs_bowler'], errors='coerce')
df['valid_ball'] = pd.to_numeric(df['valid_ball'], errors='coerce')
df['bowler_wicket'] = pd.to_numeric(df['bowler_wicket'], errors='coerce')

# Bowler Statistics

bowler_stats = df.groupby('bowler').agg(
    wickets=('bowler_wicket', 'sum'),
    runs_conceded=('runs_bowler', 'sum'),
    balls_bowled=('valid_ball', 'sum'),
    matches=('match_id', 'nunique')
).reset_index()

bowler_stats.head()

           bowler  wickets  runs_conceded  balls_bowled  matches
0  A Ashish Reddy       18            396           262       20
1        A Badoni        4             49            35        7
2      A Chandila       11            242           234       12
3     A Choudhary        5            144           101        5
4     A Dananjaya        0             47            24        1

In [133]:
# ECONOMY RATE
# Economy Rate = Total Runs Conceded / Overs Bowled

bowler_stats['overs_bowled'] = (
    bowler_stats['balls_bowled'] / 6
)

bowler_stats['economy'] = (
    bowler_stats['runs_conceded'] /
    bowler_stats['overs_bowled']
)

bowler_stats.head()

,bowler,wickets,runs_conceded,balls_bowled,matches,overs_bowled,economy
0,A Ashish Reddy,18,396,262,20,43.666667,9.068702
1,A Badoni,4,49,35,7,5.833333,8.400000
2,A Chandila,11,242,234,12,39.000000,6.205128
3,A Choudhary,5,144,101,5,16.833333,8.554455
4,A Dananjaya,0,47,24,1,4.000000,11.750000

In [ ]:
# ============================================================
# ECONOMY RATE CALCULATION
# ============================================================

# Economy Rate is one of the most important bowling metrics
# in T20 cricket. It measures how many runs a bowler concedes
# on average per over.

# Formula:
# Economy Rate = Runs Conceded / Overs Bowled

# Step 1:
# Convert total balls bowled into overs.
# Since 1 over consists of 6 balls:
#
# Overs Bowled = Balls Bowled / 6

# Step 2:
# Calculate economy rate using:
#
# Economy = Runs Conceded / Overs Bowled

# Example:
# Runs Conceded = 240
# Balls Bowled = 180
#
# Overs Bowled = 180 / 6 = 30
# Economy = 240 / 30 = 8.0

# Interpretation:
# Economy 6-7   = Excellent
# Economy 7-8   = Good
# Economy 8-9   = Average
# Economy > 9   = Poor

# Lower economy indicates better bowling performance
# because the bowler is restricting runs effectively.

# Since lower economy is better, reverse scoring was
# applied while calculating the final bowler score so
# that bowlers with lower economy receive higher scores.

In [123]:
#Genuine Bowlers
bowlers = bowler_stats[
    bowler_stats['wickets'] >= 20
].copy()

bowlers.shape

(168, 7)

In [124]:
#Check Top Bowlers
bowlers.sort_values(
    'wickets',
    ascending=False
)[[
    'bowler',
    'wickets',
    'economy',
    'matches'
]].head(15)

              bowler  wickets   economy  matches
557        YS Chahal      224  8.000517      176
76           B Kumar      205  7.719023      195
471        SP Narine      195  6.803873      191
369        PP Chawla      192  7.960519      191
380         R Ashwin      187  7.200000      217
210        JJ Bumrah      186  7.295710      150
128         DJ Bravo      183  8.384615      158
8           A Mishra      174  7.377633      162
398        RA Jadeja      173  7.679356      228
463       SL Malinga      170  7.143969      122
423      Rashid Khan      163  7.078836      140
487   Sandeep Sharma      151  8.134817      141
175         HV Patel      151  8.922267      119
176  Harbhajan Singh      150  7.078454      160
511         TA Boult      144  8.475739      122

In [125]:
#Normalize Features
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

bowlers[['wicket_score',
         'match_score']] = scaler.fit_transform(
    bowlers[['wickets',
             'matches']]
)

In [126]:
#Economy Score (Reverse)
bowlers['economy_score'] = (
    bowlers['economy'].max() -
    bowlers['economy']
)

bowlers[['economy_score']] = scaler.fit_transform(
    bowlers[['economy_score']]
)

In [127]:
#Bowler Score
# Wickets = 50%
# Economy = 30%
# Matches = 20%

bowlers['bowler_score'] = (
    bowlers['wicket_score'] * 0.50 +
    bowlers['economy_score'] * 0.30 +
    bowlers['match_score'] * 0.20
) * 100

In [128]:
#Auction Price Prediction
bowlers['estimated_price_cr'] = (
    0.2 +
    (bowlers['bowler_score'] / 100) * 24.8
)

bowlers['estimated_price_cr'] = (
    bowlers['estimated_price_cr']
    .round(2)
)

In [132]:
#Top Valuable Bowlers
top_bowlers = bowlers.sort_values(
    'estimated_price_cr',
    ascending=False
)[[
    'bowler',
    'wickets',
    'economy',
    'matches',
    'bowler_score',
    'estimated_price_cr'
]]

top_bowlers.head(15)

,bowler,wickets,economy,matches,bowler_score,estimated_price_cr
471,SP Narine,195,6.803873,191,86.918109,21.76
380,R Ashwin,187,7.200000,217,84.386850,21.13
557,YS Chahal,224,8.000517,176,83.681214,20.95
76,B Kumar,205,7.719023,195,82.883745,20.76
398,RA Jadeja,173,7.679356,228,78.379173,19.64
369,PP Chawla,192,7.960519,191,77.520126,19.42
210,JJ Bumrah,186,7.295710,150,77.249819,19.36
8,A Mishra,174,7.377633,162,74.801072,18.75
423,Rashid Khan,163,7.078836,140,72.315181,18.13
463,SL Malinga,170,7.143969,122,71.884067,18.03
176,Harbhajan Singh,150,7.078454,160,70.975081,17.80
128,DJ Bravo,183,8.384615,158,69.096508,17.34
43,AR Patel,131,7.377974,164,64.443636,16.18
487,Sandeep Sharma,151,8.134817,141,61.557411,15.47
523,UT Yadav,144,8.505236,147,57.620476,14.49

In [135]:
# ============================================================
# IPL BOWLER VALUATION MODEL
# ============================================================

# BUSINESS PROBLEM:
#
# IPL franchises invest significant amounts of money in bowlers
# during auctions. However, evaluating a bowler's true worth is
# challenging because wickets alone do not fully represent a
# bowler's effectiveness.
#
# A bowler may take wickets but also concede too many runs,
# which can negatively impact the team's performance.
#
# To address this issue, a Data-Driven Bowler Valuation Model
# was developed using historical IPL bowling performance data.

# ============================================================
# OBJECTIVE
# ============================================================
#
# To estimate the fair auction value of a bowler based on:
# 1. Total Wickets Taken
# 2. Economy Rate
# 3. Matches Played (Experience)
#
# The model helps franchises identify high-impact bowlers and
# make data-driven auction decisions.

# ============================================================
# FEATURES USED
# ============================================================
#
# 1. TOTAL WICKETS (Weight: 50%)
#    - Measures wicket-taking ability.
#    - Represents the bowler's capability to dismiss batters.
#    - Higher wickets indicate stronger match-winning impact.
#
# 2. ECONOMY RATE (Weight: 30%)
#    - Measures how many runs a bowler concedes per over.
#    - Lower economy indicates better control and efficiency.
#    - Important in T20 cricket where run restriction is critical.
#
# 3. MATCHES PLAYED (Weight: 20%)
#    - Represents player experience.
#    - Experienced bowlers are generally more reliable in
#      pressure situations and important matches.

# ============================================================
# ECONOMY RATE CALCULATION
# ============================================================
#
# Economy Rate is one of the most important bowling metrics
# in T20 cricket.
#
# Formula:
#
# Economy Rate = Runs Conceded / Overs Bowled
#
# Step 1:
# Convert total balls bowled into overs.
#
# Overs Bowled = Balls Bowled / 6
#
# Step 2:
# Calculate economy rate.
#
# Economy Rate = Runs Conceded / Overs Bowled
#
# Example:
#
# Runs Conceded = 240
# Balls Bowled = 180
#
# Overs Bowled = 180 / 6 = 30
#
# Economy Rate = 240 / 30 = 8.0
#
# Interpretation:
#
# Economy 6-7   = Excellent
# Economy 7-8   = Good
# Economy 8-9   = Average
# Economy > 9   = Poor
#
# Since lower economy is better, reverse scoring was applied
# so that bowlers with lower economy receive higher scores.

# ============================================================
# PLAYER SCORE CALCULATION
# ============================================================
#
# All bowling metrics were normalized using MinMax Scaling
# to bring them onto the same scale.
#
# Bowler Score Formula:
#
# Bowler Score =
# (Wicket Score × 50%)
# + (Economy Score × 30%)
# + (Match Experience Score × 20%)
#
# Final score is calculated on a scale of 0–100.

# ============================================================
# AUCTION PRICE ESTIMATION
# ============================================================
#
# IPL auctions have a minimum base price for players.
#
# Assumptions:
#
# Minimum Auction Price = ₹20 Lakh (0.20 Cr)
# Maximum Auction Price = ₹25 Crore
#
# Estimated Auction Price Formula:
#
# Estimated Price (Cr) =
# 0.20 + (Bowler Score / 100) × 24.80
#
# This ensures:
#
# - No player value falls below the IPL base price.
# - Elite bowlers receive realistic auction valuations.
# - Better performance results in higher auction value.

# ============================================================
# BUSINESS INSIGHTS
# ============================================================
#
# Bowlers with:
#
# - High wicket-taking ability
# - Low economy rates
# - Extensive IPL experience
#
# receive higher valuation scores and estimated auction prices.
#
# Example:
#
# Bowlers such as Jasprit Bumrah, Yuzvendra Chahal,
# Bhuvneshwar Kumar and Ravichandran Ashwin are expected
# to receive higher valuations because of their consistent
# wicket-taking ability, strong economy rates and experience.
#
# The model rewards both attacking bowlers (wickets)
# and defensive bowlers (economy control).

# ============================================================
# CONCLUSION
# ============================================================
#
# This Bowler Valuation Model converts historical bowling
# performance into an estimated auction value.
#
# The model provides IPL franchises with a structured and
# data-driven approach for evaluating bowlers during auctions.
#
# Instead of relying solely on reputation or subjective
# judgment, franchises can use objective bowling metrics
# to reduce investment risk and make smarter auction decisions.
#
# ============================================================

In [136]:
# IPL ALL-ROUNDER VALUATION MODEL

In [137]:
#CREATE ALL-ROUNDER DATASET
all_rounders = player_stats[
    (player_stats['total_runs'] >= 1000) &
    (player_stats['wickets'] >= 30)
].copy()

all_rounders.head()

         player  total_runs  balls  matches  strike_rate  wickets
40   AD Russell        2655   1525      114   174.098361    123.0
58     AR Patel        1919   1436      126   133.635097    131.0
162    DJ Bravo        1560   1204      110   129.568106    183.0
214  GJ Maxwell        2820   1818      134   155.115512     41.0
224   HH Pandya        2839   1927      144   147.327452     80.0

In [145]:
# MERGE ECONOMY DATA FROM BOWLER DATASET
all_rounders = all_rounders.merge(
    bowler_stats[['bowler','economy']],
    left_on='player',
    right_on='bowler',
    how='left'
)

all_rounders.drop(columns=['bowler'], inplace=True)

all_rounders.head()

,player,total_runs,balls,matches,strike_rate,wickets,bowler_x,economy_x,runs_score,sr_score,wicket_score,match_score,bowler_y,economy_y,economy
0,AD Russell,2655,1525,114,174.098361,123.0,AD Russell,9.511628,0.574653,1.000000,0.558282,0.419580,AD Russell,9.511628,9.511628
1,AR Patel,1919,1436,126,133.635097,131.0,AR Patel,7.377974,0.319097,0.376264,0.607362,0.503497,AR Patel,7.377974,7.377974
2,DJ Bravo,1560,1204,110,129.568106,183.0,DJ Bravo,8.384615,0.194444,0.313572,0.926380,0.391608,DJ Bravo,8.384615,8.384615
3,GJ Maxwell,2820,1818,134,155.115512,41.0,GJ Maxwell,8.295499,0.631944,0.707382,0.055215,0.559441,GJ Maxwell,8.295499,8.295499
4,HH Pandya,2839,1927,144,147.327452,80.0,HH Pandya,9.268235,0.638542,0.587330,0.294479,0.629371,HH Pandya,9.268235,9.268235

In [146]:
#NORMALIZE FEATURES
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

all_rounders[['runs_score',
              'sr_score',
              'wicket_score',
              'match_score']] = scaler.fit_transform(

    all_rounders[['total_runs',
                  'strike_rate',
                  'wickets',
                  'matches']]
)

all_rounders.head()

,player,total_runs,balls,matches,strike_rate,wickets,bowler_x,economy_x,runs_score,sr_score,wicket_score,match_score,bowler_y,economy_y,economy
0,AD Russell,2655,1525,114,174.098361,123.0,AD Russell,9.511628,0.574653,1.000000,0.558282,0.419580,AD Russell,9.511628,9.511628
1,AR Patel,1919,1436,126,133.635097,131.0,AR Patel,7.377974,0.319097,0.376264,0.607362,0.503497,AR Patel,7.377974,7.377974
2,DJ Bravo,1560,1204,110,129.568106,183.0,DJ Bravo,8.384615,0.194444,0.313572,0.926380,0.391608,DJ Bravo,8.384615,8.384615
3,GJ Maxwell,2820,1818,134,155.115512,41.0,GJ Maxwell,8.295499,0.631944,0.707382,0.055215,0.559441,GJ Maxwell,8.295499,8.295499
4,HH Pandya,2839,1927,144,147.327452,80.0,HH Pandya,9.268235,0.638542,0.587330,0.294479,0.629371,HH Pandya,9.268235,9.268235

In [147]:
# ECONOMY SCORE
# Lower Economy = Better

all_rounders['economy_score'] = (
    all_rounders['economy'].max()
    - all_rounders['economy']
)

all_rounders[['economy_score']] = scaler.fit_transform(
    all_rounders[['economy_score']]
)

In [149]:
# ALL-ROUNDER SCORE CALCULATION
# Weightage:
# Runs      = 30%
# StrikeRate= 15%
# Wickets   = 30%
# Economy   = 15%
# Matches   = 10%

all_rounders['all_rounder_score'] = (

    all_rounders['runs_score'] * 0.30 +

    all_rounders['sr_score'] * 0.15 +

    all_rounders['wicket_score'] * 0.30 +

    all_rounders['economy_score'] * 0.15 +

    all_rounders['match_score'] * 0.10

) * 100

In [156]:
# AUCTION PRICE ESTIMATION
# Minimum Price = ₹20 Lakh
# Maximum Price = ₹25 Crore

all_rounders['estimated_price_cr'] = (

    0.20 +

    (all_rounders['all_rounder_score'] / 100) * 24.80

).round(2)

In [157]:
# TOP VALUABLE ALL-ROUNDERS
top_all_rounders = all_rounders.sort_values(
    'estimated_price_cr',
    ascending=False
)[[
    'player',
    'total_runs',
    'strike_rate',
    'wickets',
    'economy',
    'matches',
    'all_rounder_score',
    'estimated_price_cr'
]]

top_all_rounders.head(20)

,player,total_runs,strike_rate,wickets,economy,matches,all_rounder_score,estimated_price_cr
14,RA Jadeja,3336,130.007794,173.0,7.679356,197,75.762643,18.99
15,SP Narine,1816,166.605505,195.0,6.803873,120,71.382864,17.90
16,SR Watson,3880,137.931034,92.0,7.931000,141,63.193594,15.87
0,AD Russell,2655,174.098361,123.0,9.511628,114,54.801445,13.79
7,KA Pollard,3437,147.574066,69.0,8.790323,168,54.216698,13.65
17,YK Pathan,3222,143.518931,42.0,7.401918,153,51.883044,13.07
1,AR Patel,1919,133.635097,131.0,7.377974,126,50.635353,12.76
2,DJ Bravo,1560,129.568106,183.0,8.384615,110,49.431981,12.46
4,HH Pandya,2839,147.327452,80.0,9.268235,144,45.914761,11.59
3,GJ Maxwell,2820,155.115512,41.0,8.295499,134,44.447916,11.22
8,KH Pandya,1757,131.906907,100.0,7.538400,115,41.280636,10.44
18,Yuvraj Singh,2754,129.783223,36.0,7.436133,126,40.670524,10.29
6,JH Kallis,2427,109.225923,65.0,7.897819,95,33.398780,8.48
5,IK Pathan,1150,121.052632,80.0,7.779736,82,25.266545,6.47
11,MP Stoinis,2045,145.035461,44.0,9.838926,102,24.730638,6.33
10,MM Ali,1167,139.760479,41.0,7.229508,59,23.702371,6.08
13,R Tewatia,1146,137.081340,32.0,7.907473,80,19.325557,4.99
12,MR Marsh,1407,141.977800,37.0,8.517857,54,19.261873,4.98
9,MC Henriques,1000,126.903553,42.0,8.141053,54,14.319286,3.75

In [158]:
# ============================================================
# IPL ALL-ROUNDER VALUATION MODEL
# ============================================================

# BUSINESS PROBLEM:
#
# All-rounders are among the most valuable players in IPL because
# they contribute in both batting and bowling departments.
#
# However, evaluating an all-rounder's true value is difficult
# because franchises must assess both batting and bowling
# performance simultaneously.
#
# A player may score many runs but contribute little with the ball,
# while another player may take wickets but have limited batting impact.
#
# To address this challenge, a Data-Driven All-Rounder Valuation
# Model was developed using historical IPL batting and bowling data.

# ============================================================
# OBJECTIVE
# ============================================================
#
# To estimate the fair auction value of an all-rounder based on:
#
# 1. Total Runs Scored
# 2. Strike Rate
# 3. Total Wickets Taken
# 4. Economy Rate
# 5. Matches Played (Experience)
#
# The model helps franchises identify high-impact players who
# contribute in multiple aspects of the game.

# ============================================================
# FEATURES USED
# ============================================================
#
# 1. TOTAL RUNS (Weight: 30%)
#    - Measures batting contribution and consistency.
#    - Higher runs indicate greater impact with the bat.
#
# 2. STRIKE RATE (Weight: 15%)
#    - Measures scoring speed.
#    - Higher strike rate indicates aggressive batting.
#
# 3. TOTAL WICKETS (Weight: 30%)
#    - Measures bowling contribution.
#    - Higher wickets indicate stronger bowling impact.
#
# 4. ECONOMY RATE (Weight: 15%)
#    - Measures bowling efficiency.
#    - Lower economy indicates better control over runs.
#
# 5. MATCHES PLAYED (Weight: 10%)
#    - Represents player experience and reliability.
#    - Experienced players are more effective under pressure.

# ============================================================
# ECONOMY RATE CALCULATION
# ============================================================
#
# Economy Rate is used to measure bowling efficiency.
#
# Formula:
#
# Economy Rate = Runs Conceded / Overs Bowled
#
# Step 1:
# Convert total balls bowled into overs.
#
# Overs Bowled = Balls Bowled / 6
#
# Step 2:
# Calculate economy rate.
#
# Economy Rate = Runs Conceded / Overs Bowled
#
# Example:
#
# Runs Conceded = 300
# Balls Bowled = 240
#
# Overs Bowled = 240 / 6 = 40
#
# Economy Rate = 300 / 40 = 7.5
#
# Interpretation:
#
# Economy 6-7   = Excellent
# Economy 7-8   = Good
# Economy 8-9   = Average
# Economy > 9   = Poor
#
# Since lower economy is better, reverse scoring was applied
# so that players with lower economy receive higher scores.

# ============================================================
# PLAYER SCORE CALCULATION
# ============================================================
#
# All performance metrics were normalized using MinMax Scaling
# to bring them onto the same scale.
#
# All-Rounder Score Formula:
#
# All-Rounder Score =
#
# (Runs Score × 30%)
# + (Strike Rate Score × 15%)
# + (Wicket Score × 30%)
# + (Economy Score × 15%)
# + (Match Experience Score × 10%)
#
# Final score is calculated on a scale of 0–100.

# ============================================================
# AUCTION PRICE ESTIMATION
# ============================================================
#
# IPL auctions have a minimum base price for players.
#
# Assumptions:
#
# Minimum Auction Price = ₹20 Lakh (0.20 Cr)
# Maximum Auction Price = ₹25 Crore
#
# Estimated Auction Price Formula:
#
# Estimated Price (Cr) =
#
# 0.20 + (All-Rounder Score / 100) × 24.80
#
# This ensures:
#
# - No player value falls below the IPL base price.
# - Elite all-rounders receive realistic auction valuations.
# - Better overall performance results in higher auction value.

# ============================================================
# BUSINESS INSIGHTS
# ============================================================
#
# Players with:
#
# - Strong batting performance
# - High strike rates
# - Consistent wicket-taking ability
# - Low economy rates
# - Extensive IPL experience
#
# receive higher valuation scores and estimated auction prices.
#
# Examples:
#
# Ravindra Jadeja
# Hardik Pandya
# Andre Russell
# Sunil Narine
# Shane Watson
#
# These players are expected to receive premium auction
# valuations because they contribute significantly in both
# batting and bowling departments.
#
# The model rewards complete cricketers who provide value
# across multiple phases of the game.

# ============================================================
# BUSINESS VALUE
# ============================================================
#
# This model helps IPL franchises:
#
# ✓ Identify high-impact all-rounders
# ✓ Optimize auction spending
# ✓ Reduce investment risk
# ✓ Improve team balance
# ✓ Make data-driven decisions
#
# Since all-rounders contribute in multiple roles,
# they often provide a higher return on investment
# compared to specialist players.

# ============================================================
# CONCLUSION
# ============================================================
#
# This All-Rounder Valuation Model converts historical
# batting and bowling performance into an estimated
# auction value.
#
# By combining batting ability, bowling effectiveness,
# and experience, the model provides a comprehensive
# assessment of player value.
#
# Instead of relying solely on reputation or recent form,
# franchises can use objective performance metrics to
# identify the most valuable all-rounders in the IPL.
#
# ============================================================

In [ ]:
# We developed three separate valuation models because the performance indicators of batters, bowlers, and all-rounders are fundamentally different. 
# This allowed us to estimate auction values more accurately and realistically based on role-specific performance metrics.